apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bl02t
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: esq51579
  destination:
    name: argus
    namespace: esq51579
  source:
    path: apps
    repoURL: https://github.com/marcelldls/bl02t
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
