apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
{{- $config_path := .Release.Name -}}
# contents of the ioc instance config folder
{{ (.Files.Glob "$config_path/*").AsConfig | indent 2 }}
