project: esq51579
destination:
  name: argus
  namespace: esq51579
source:
  repoURL: https://github.com/gilesknap/bl02t.git
  targetRevision: main

services:
  - service: epics-pvcs
  - service: epics-opis
  - service: bl02t-ea-test-01
    chart: ioc-instance
    repoURL: ghcr.io/epics-containers/ioc-instance
    targetRevision: 3.5.2+b3
